export const MINESWEEPER_STATE_BLOCKED = 'MINESWEEPER_STATE_BLOCKED';
export const MINESWEEPER_STATE_ERROR = 'MINESWEEPER_STATE_ERROR';
export const MINESWEEPER_STATE_FAILED = 'MINESWEEPER_STATE_FAILED';
export const MINESWEEPER_STATE_FLAGGED = 'MINESWEEPER_STATE_FLAGGED';
export const MINESWEEPER_STATE_HIDDEN = 'MINESWEEPER_STATE_HIDDEN';
export const MINESWEEPER_STATE_VISIBLE = 'MINESWEEPER_STATE_VISIBLE';

export const MINESWEEPER_STATUS_GAME_OVER = 'STATUS_GAME_OVER';
export const MINESWEEPER_STATUS_RUNNING = 'STATUS_RUNNING';
export const MINESWEEPER_STATUS_WIN = 'STATUS_WIN';

export const MINESWEEPER_VALUE_MINE = 'MINESWEEPER_VALUE_MINE';
